apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db-service.fullname" . }}
  labels:
    app: {{ include "db-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "db-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "db-service.name" . }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
