apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: postgresql
  type: {{ .Values.service.type }}
