apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
  selector:
    app: postgresql
  type: {{ .Values.postgresql.service.type }}
