replicaCount: 1

image:
  repository: ubuntu/squid
  tag: 5.2-22.04_beta
  pullPolicy: IfNotPresent

ports:
  - 3128
  - 3129
  - 3130
  - 3131
  - 3132
  - 3133
  - 3134
  - 3135
  - 3136
  - 3137
  - 3138
  - 3139
  - 3140
  - 3141
  - 3142
  - 3143
  - 3144
  - 3145
  - 3146
  - 3147

hostNetwork: true

nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k8s-master
proxyRouter:
  enabled: true
  port: 8080
  image:
    repository: python
    tag: "3.11-slim"
    pullPolicy: IfNotPresent
