apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: harbor-gateway
  namespace: registry
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 32001
        name: http-harbor
        protocol: HTTP
      hosts:
        - {{ .Values.global.hostname | quote }}
