apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor-virtualservice
  namespace: registry
spec:
  hosts:
    - {{ .Values.global.hostname | quote }}
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: {{ .Values.global.harborUriPrefix | quote }}
      rewrite:
        uri: /
      route:
        - destination:
            host: docker-registry-harbor-core.registry.svc.cluster.local
            port:
              number: 80
