apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfsserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfsserver
  template:
    metadata:
      labels:
        app: nfsserver
    spec:
      hostNetwork: true
      containers:
        - name: nfsserver
          image: k8s.gcr.io/volume-nfs:0.8
          ports:
            - containerPort: 2049
              name: nfs
          securityContext:
            privileged: true
          volumeMounts:
            - name: export-volume
              mountPath: /exports
      volumes:
        - name: export-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
