{{ if index .Values "nfs-server" "storageClass" "create" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ index .Values "nfs-server" "storageClass" "name" }}
provisioner: example.com/nfs
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"
mountOptions:
{{ toYaml (index .Values "nfs-server" "nfs" "mountOptions") | indent 2 }}
reclaimPolicy: Retain
volumeBindingMode: Immediate
{{ end }}
