apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.global.hostname | quote }}
    - name: http-harbor
      port: 32001
      targetPort: 8080
      protocol: TCP
      nodePort: 32001
