controller:
  admin:
    existingSecret: jenkins-admin-creds
  serviceType: NodePort
  nodePort: 32000

persistence:
  storageClass: local-path
  size: 5Gi

serviceAccount:
  create: true

serviceAccountAgent:
  create: true
