apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: argocd
spec:
  hosts:
    - {{ .Values.global.hostname | quote }}
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: {{ .Values.global.argocdUriPrefix | quote }}
      rewrite:
        uri: /
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
