image:
  repository: 8761.online-vds.ru:32001/db-service/db-service
  tag: "1.0.5"
  pullPolicy: Always

imagePullSecrets:
  - name: harbor-creds

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

replicaCount: 1
