global:
  istioNamespace: istio-system

base:
  enableCRDTemplates: true
  excludedCRDs: []
  validationURL: ""
  validationCABundle: ""
  enableIstioConfigCRDs: true

defaultRevision: "default"

experimental:
  stableValidationPolicy: false