apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: squid-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: squid-proxy
  template:
    metadata:
      labels:
        app: squid-proxy
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        privileged: true
      affinity:
        nodeAffinity: {{ toYaml .Values.nodeAffinity | nindent 10 }}
      containers:
        - name: squid
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args:
            - -c
            - |
              squid -z -f /etc/squid/squid.conf
              squid -N -f /etc/squid/squid.conf
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ . }}
              name: squid-{{ . }}
            {{- end }}
          volumeMounts:
            - name: squid-config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
      volumes:
        - name: squid-config
          configMap:
            name: squid-config
