apiVersion: v1
kind: Service
metadata:
  name: proxy-router
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: squid-proxy
  ports:
    - name: http-proxy
      port: 8080
      targetPort: 8080
      protocol: TCP
