zookeeper:
  image: bitnami/zookeeper:3.9.1
  replicas: 1
  storage: 1Gi
  port: 2181
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

kafka:
  image: bitnami/kafka:3.6.1
  replicas: 1
  storage: 2Gi
  port: 9092
  externalAccess:
    enabled: false
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

