apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telegram-message.fullname" . }}
  labels:
    app: {{ include "telegram-message.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "telegram-message.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "telegram-message.name" . }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      env:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: telegram-message-config
              mountPath: /app/config/application.properties
              subPath: application.properties
          env:
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: telegram-message-config
                key: JAVA_OPTS
      volumes:
        - name: telegram-message-config
          configMap:
            name: telegram-message-config
