apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tg-message.fullname" . }}
  labels:
    app: {{ include "tg-message.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tg-message.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tg-message.name" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tg-message-config
              mountPath: /app/config/applocation.properties
              subPath: applocation.properties
      volumes:
        - name: tg-message-config
          configMap:
            name: tg-message-config
